### ISSUE TITLE
Invalid types in composite responses

### ISSUE THREAD

**Issue by timoniq** [telefone-org/types#1]
In unions:

https://github.com/telefone-org/types/blob/4b8de73935bba44c2398de12fd474d658ec108cd/telefone_types/methods.py#L1195-L1197

In lists:

https://github.com/telefone-org/types/blob/4b8de73935bba44c2398de12fd474d658ec108cd/telefone_types/methods.py#L1206-L1210

Method types have to be regenerated with composite types in mind.

Also I propose making type generator public.

**Comment by exthrempty** [comment]
The issue was resolved in a recent commit.

Now unions: 

https://github.com/telefone-org/types/blob/abb8060730947eea13367bc9847ee85d307ff293/telefone_types/methods.py#L1189-L1195

And the lists: 

https://github.com/telefone-org/types/blob/abb8060730947eea13367bc9847ee85d307ff293/telefone_types/methods.py#L1204-L1206

are handled properly. Thanks for the contribution! 

Regarding your proposal, type generator will be public as soon as its architecture matures. I will post an update here when it happens.

**Comment by exthrempty** [comment]
The workaround above has been replaced in version `^6.1.0.1` in favor of a simpler, but more library-dependent approach. Now responses with composite types are being gracefully handled by `pydantic.parse_obj_as`.

https://github.com/telefone-org/types/blob/3ff3aca68b3463112ee3b640ecc3fd24d16c1edf/telefone_types/methods.py#L1222-L1224

https://github.com/telefone-org/types/blob/3ff3aca68b3463112ee3b640ecc3fd24d16c1edf/telefone_types/methods.py#L1233-L1237
